# # See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# # This stage is used when running from VS in fast mode (Default for Debug configuration)
# FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
# USER $APP_UID
# WORKDIR /app

# EXPOSE 9455

# ENV ASPNETCORE_URLS=http://+:9455


# # This stage is used to build the service project
# FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# ARG BUILD_CONFIGURATION=Release
# WORKDIR /src
# COPY ["WarrantyManagement.API.csproj", "WarrantyManagement.API/"]
# RUN dotnet restore "./WarrantyManagement.API/WarrantyManagement.API.csproj"
# COPY . ./WarrantyManagement.API
# WORKDIR "/src/WarrantyManagement.API"
# RUN dotnet build "./WarrantyManagement.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# # This stage is used to publish the service project to be copied to the final stage
# FROM build AS publish
# ARG BUILD_CONFIGURATION=Release
# RUN dotnet publish "./WarrantyManagement.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# # This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
# FROM base AS final
# WORKDIR /app
# COPY --from=publish /app/publish .
# ENTRYPOINT ["dotnet", "WarrantyManagement.API.dll"]

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /src

# Copy csproj files first (layer caching)
COPY WarrantyManagement.API/*.csproj WarrantyManagement.API/
COPY WarrantyManagement.DAL/*.csproj WarrantyManagement.DAL/
COPY WarrantyManagement.BLL/*.csproj WarrantyManagement.BLL/

# Restore dependencies
RUN dotnet restore WarrantyManagement.API/WarrantyManagement.API.csproj

# Copy everything else
COPY . .

# Build the project so dependencies are available
RUN dotnet build WarrantyManagement.API/WarrantyManagement.API.csproj -c Debug

# Expose ports
EXPOSE 9455

ENV ASPNETCORE_ENVIRONMENT=Development

WORKDIR /src/WarrantyManagement.API
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:9455"]