# Project identification
sonar.projectKey=warranty-management-be-dev
sonar.projectName=Warranty Management API
sonar.projectVersion=1.0

# Where the source code is
sonar.sources=WarrantyManagement.API
sonar.exclusions=**/bin/**,**/obj/**

# .NET specific
sonar.language=cs

# Test and coverage
# sonar.tests=WarrantyManagement.Tests
# sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

# Encoding
sonar.sourceEncoding=UTF-8
