// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarrantyManagement.DAL.Data.Context;

#nullable disable

namespace WarrantyManagement.DAL.Migrations
{
    [DbContext(typeof(WarrantyDbContext))]
    partial class WarrantyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.ClaimDetail", b =>
                {
                    b.Property<Guid>("ClaimDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartItemId")
                        .HasColumnType("uuid");

                    b.HasKey("ClaimDetailId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PartItemId");

                    b.ToTable("ClaimDetails");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.ClaimImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("ImageId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimImages");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.CustomerVehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("text");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MileAge")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VIN");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerVehicles");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("InventoryId");

                    b.HasIndex("CenterId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Part", b =>
                {
                    b.Property<Guid>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("PartId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.PartItem", b =>
                {
                    b.Property<Guid>("PartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartItemId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("PartId");

                    b.ToTable("PartItems");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ReportId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.ServiceCenter", b =>
                {
                    b.Property<Guid>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CenterId");

                    b.ToTable("ServiceCenters");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServiceCenterId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("ServiceCenterId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.VehiclePart", b =>
                {
                    b.Property<Guid>("VehiclePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehiclePartId");

                    b.HasIndex("PartId");

                    b.HasIndex("VIN");

                    b.ToTable("VehicleParts");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.WarrantyClaim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("ClaimId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.HasIndex("VIN");

                    b.ToTable("WarrantyClaims");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.WarrantyPolicy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DurationMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("PolicyId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimateHour")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.ClaimDetail", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.WarrantyClaim", "WarrantyClaim")
                        .WithMany("ClaimDetails")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.PartItem", "PartItem")
                        .WithMany("ClaimDetails")
                        .HasForeignKey("PartItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PartItem");

                    b.Navigation("WarrantyClaim");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.ClaimImage", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.WarrantyClaim", "WarrantyClaim")
                        .WithMany("Images")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WarrantyClaim");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.CustomerVehicle", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.Campaign", "Campaign")
                        .WithMany("CustomerVehicles")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.Customer", "Customer")
                        .WithMany("CustomerVehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Inventory", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.ServiceCenter", "ServiceCenter")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceCenter");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Part", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.WarrantyPolicy", "WarrantyPolicy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Parts")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WarrantyPolicy");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.PartItem", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.Inventory", "Inventory")
                        .WithMany("PartItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.Part", "Part")
                        .WithMany("PartItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Report", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.WarrantyClaim", "WarrantyClaim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WarrantyClaim");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.User", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.ServiceCenter", "ServiceCenter")
                        .WithMany("Users")
                        .HasForeignKey("ServiceCenterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ServiceCenter");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.VehiclePart", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.Part", "Part")
                        .WithMany("VehicleParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.CustomerVehicle", "Vehicle")
                        .WithMany("VehicleParts")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.WarrantyClaim", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.WarrantyPolicy", "WarrantyPolicy")
                        .WithMany("warrantyClaims")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.User", "User")
                        .WithMany("WarrantyClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.CustomerVehicle", "CustomerVehicle")
                        .WithMany()
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerVehicle");

                    b.Navigation("User");

                    b.Navigation("WarrantyPolicy");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.WorkOrder", b =>
                {
                    b.HasOne("WarrantyManagement.DAL.Data.Entities.WarrantyClaim", "WarrantyClaim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarrantyManagement.DAL.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");

                    b.Navigation("WarrantyClaim");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Campaign", b =>
                {
                    b.Navigation("CustomerVehicles");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Customer", b =>
                {
                    b.Navigation("CustomerVehicles");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.CustomerVehicle", b =>
                {
                    b.Navigation("VehicleParts");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Inventory", b =>
                {
                    b.Navigation("PartItems");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.Part", b =>
                {
                    b.Navigation("PartItems");

                    b.Navigation("VehicleParts");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.PartItem", b =>
                {
                    b.Navigation("ClaimDetails");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.ServiceCenter", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.User", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("WarrantyClaims");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.WarrantyClaim", b =>
                {
                    b.Navigation("ClaimDetails");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.WarrantyPolicy", b =>
                {
                    b.Navigation("warrantyClaims");
                });

            modelBuilder.Entity("WarrantyManagement.DAL.Data.Entities.WorkOrder", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
